# Generated by Django 4.1.2 on 2022-12-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='movie',
        ),
    ]
