# Generated by Django 4.1.2 on 2022-12-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.SmallIntegerField(default=0),
        ),
    ]
